<?php if (!$this->isVatNumberValid()) { ?>
<script>
    window.onload = function () {

        let taxvatInput = document.getElementById('taxvat');
        taxvatInput.classList.add('validation-failed');
        let errorDiv = null;
        errorDiv = document.createElement("div");
        errorDiv.innerHTML = '<p class="validation-advice">Your VAT number is not valid.</p>';
        taxvatInput.parentNode.insertBefore(errorDiv, taxvatInput.nextSibling);
    }
</script>
<?php } ?>