<ul class="form-list checkout-agreements" id="payment_form_tlbarion" style="display:none;">
    <li>
        <div class="agreement-content">
            <?php echo $this->getBarionPaymentInstructions(); ?>
        </div>
    </li>

    <img src="<?php echo Mage::getUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>virtua/barionpayment/payments.png" alt="Barion" />
    <?php if (Mage::getSingleton('core/session')->getBarionToken() && Mage::getModel('tlbarion/paymentmethod')->isTokenPaymentEnabled()) { ?>
    <div class="reset-token">
        <?php echo $this->__('You have been automatically approved to 1 click payment. If you push the "Pay and order in 1 click" button, you will not be redirected and the payment will be proceeded immediately.'); ?><br>
        <?php echo $this->__('If you want to reset the 1 click payment please click on "Reset the 1 click payment".'); ?><br>
        <a href="<?php echo Mage::getUrl('tlbarion/redirection/removeToken'); ?>"><?php echo $this->__('Reset the 1 click payment'); ?></a>
    </div>
    <?php } ?>
</ul>