<ul class="form-list checkout-agreements" id="payment_form_tlbarion" style="display:none;">
    <li>
        <div class="agreement-content">
            <?php echo $this->getBarionPaymentInstructions(); ?>
        </div>
    </li>

    <img src="<?php echo Mage::getUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>virtua/barionpayment/payments.png" alt="Barion" />
    <?php if (Mage::getSingleton('core/session')->getBarionToken()) { ?>
    <div class="reset-token">
        <?php echo $this->__('You are using token already.'); ?><br>
        <a href="<?php echo Mage::getUrl('tlbarion/redirection/removeToken'); ?>"><?php echo $this->__('Reset token'); ?></a>
    </div>
    <?php } ?>
</ul>