<?php
$_product = $this->getProduct();
?>

<?php if(Mage::registry('current_product')): ?>
    <!-- Google Code for Remarketing Tag -->
    <!--------------------------------------------------
    Remarketing tags may not be associated with personally identifiable information or placed on pages related to sensitive categories. See more information and instructions on how to setup the tag on: http://google.com/ads/remarketingsetup
    --------------------------------------------------->
    <script type="text/javascript">
        var google_tag_params =
            {
                dynx_itemid: '<?php echo $_product->getSku() ?>',
                dynx_pagetype: 'offerdetail',
                dynx_totalvalue: <?php echo $_product->getFinalPrice() ?>,
                ecomm_prodid: '<?php echo $_product->getSku() ?>',
                ecomm_pagetype: 'product',
                ecomm_totalvalue: <?php echo $_product->getFinalPrice() ?>,
            }
        ;
    </script>
    <script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = 1036701238;
        var google_custom_params = window.google_tag_params;
        var google_remarketing_only = true;
        /* ]]> */
    </script>
    <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
    </script>
    <noscript>
        <div style="display:inline;">
            <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/1036701238/?guid=ON&script=0"/>
        </div>
    </noscript>
<? endif; ?>
