<?php
$position = 1;
?>
<?php if($crumbs && is_array($crumbs)): ?>
<div class="col-sm-12 a-left">
    <ul itemscope itemtype="http://schema.org/BreadcrumbList">
        <?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
            <li class="<?php echo $_crumbName ?>" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
            <?php if($_crumbInfo['link']): ?>
                <a itemscope itemtype="http://schema.org/Thing" itemprop="item" href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->escapeHtml($_crumbInfo['title']) ?>">
                    <link itemprop="url" href="<?php echo $_crumbInfo['link']; ?>">
                    <span itemprop="name"><?php echo $this->escapeHtml($_crumbInfo['label']) ?></span>
                </a>
            <?php elseif($_crumbInfo['last']): ?>
                <a itemscope itemtype="http://schema.org/Thing" itemprop="item" href="<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>">
                    <link itemprop="url" href="<?php echo (isset($_crumbInfo['link']) && $_crumbInfo['link']) ? $_crumbInfo['link'] : Mage::helper('core/url')->getCurrentUrl(); ?>">
                    <strong itemprop="name"><?php echo $this->escapeHtml($_crumbInfo['label']) ?></strong>
                </a>
            <?php else: ?>
                <?php echo $this->escapeHtml($_crumbInfo['label']) ?>
            <?php endif; ?>
            <?php if(!$_crumbInfo['last']): ?>
                <span class="breadcrumbs-split"><i class="icon-right-open"></i></span>
            <?php endif; ?>
                <meta itemprop="position" content="<?php echo $position; ?>" />
            </li>
            <?php $position++; ?>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
